[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
bcf_core = "7zE... (Placeholder)"

[programs.devnet]
bcf_core = "7zE... (Placeholder)"

[programs.mainnet]
bcf_core = "7zE... (Placeholder)"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
