[features]
seeds = false
skip-lint = false

[programs.devnet]
bags-creator-fund = "ELarLMHYVxR2TndqEc6kHUSvwRyZUPHJ5BHFcD7yQtcJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = ["programs/bags-creator-fund"]
